#' Project new data into a known factor space
#'
#' @description
#' This function uses the feature weights learned by a MOFA2 model to project unseen data to the factor space
#'
#' @details
#' This function calculates the pseudoinverse of the feature weights of a `MOFA2` model and uses it to
#' project unseen data into the factor space. Only shared features are used for the projection
#'
#' @param model A MOFA2 model.
#' @param test_data A dataframe in multiview representation as generated by `MOFAcellulaR::pb_dat2MOFA`
#'
#' @return A matrix with samples in rows and projected factors in columns
#' @export
#'
#' @import MOFA2
#' @import tibble
#' @import dplyr
#' @import tidyr
#' @import MASS
#'
#' @examples
#' inputs_dir <- base::system.file("extdata", package = "MOFAcellulaR")
#' load(file.path(inputs_dir, "testpbcounts.rda"))
#' load(file.path(inputs_dir, "testcoldata.rda"))
#' pb_obj <- create_init_exp(counts = testpbcounts,  coldata = testcoldata)
#'
#' ct_list <- filt_profiles(pb_dat = pb_obj,
#'                          cts = c("Fib","CM"),
#'                          ncells = 5,
#'                          counts_col = "cell_counts",
#'                          ct_col = "cell_type")
#'
#' ct_list <- filt_gex_byexpr(pb_dat_list = ct_list,
#'                            min.count = 5,
#'                            min.prop = 0.25)
#'
#' ct_list <- tmm_trns(pb_dat_list = ct_list,
#'                     scale_factor = 1000000)
#'
#' ct_list <- center_views(pb_dat_list = ct_list)
#'
#' multiview_dat <- pb_dat2MOFA(pb_dat_list = ct_list)
#'
#' trained_model <- MOFA2::load_model(file.path(inputs_dir, "testmodel.hdf5"))
#'
#' projected_factors <- project_data(model = trained_model, test_data = multiview_dat)
#'
#'
project_data <- function(model, test_data) {

  # 1. get loading matrix
  loading_matrix <- MOFA2::get_weights(model,
                                       as.data.frame = T) %>%
    base::as.data.frame() %>%
    dplyr::select(-view) %>%
    tidyr::pivot_wider(names_from = feature) %>%
    tibble::column_to_rownames("factor") %>%
    base::as.matrix()

  # 2. calculate pseudo-inverse
  # returns features in rows, factors in columns
  inv_loading <- MASS::ginv(loading_matrix)
  rownames(inv_loading) <- colnames(loading_matrix)
  colnames(inv_loading) <- rownames(loading_matrix)

  # 3. prepare test data
  # test data should be transposed so as to have patients in rows, features in columns
  test_data_mat <- test_data %>%
    dplyr::select(-view) %>%
    tidyr::pivot_wider(names_from = sample,
                       values_from = value,
                       values_fill = 0) %>%
    tibble::column_to_rownames("feature") %>%
    base::as.matrix() %>%
    base::t()

  # 4. check shared features
  shared_features <- intersect(rownames(inv_loading),
                               colnames(test_data_mat))

  inv_loading <- inv_loading[shared_features, ]

  test_data_mat <- test_data_mat[, shared_features]

  # 5. project test data
  projected_factors <- test_data_mat %*% inv_loading

  return(projected_factors)
}
